### ISSUE TITLE
Email service

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/auth-sso#23]
25.000 free emails: https://postmarkapp.com/
- [ ] create account in postmarkapp
- [ ] create email service using postmarkapp.com - use the IEmailService interface
- [ ] configuration in external file appsettings.override.json, added in .gitignore, not tracked
- [ ] specification for configuring appsettings.override.json
- [ ] inject email service in account confirmation
- [ ] test email

**Comment by timotei** [comment]
Mă gândesc că s-a ales postmark chiar dacă e unul dintre cele mai scumpe pentru că e mai rapid/reliable?

**Comment by alexchiraples** [comment]
S-a ales postmark pentru ca are 25k de mail-uri free si e ideal pentru dezvoltare. Vom folosi un server de smtp in productie. Va aparea si un task de smtp, sunt in lucru.
