### ISSUE TITLE
Audit trail

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/auth-sso#24]
Audit the following attributes: UserName, IpAddress, AreaAccessed, TimeStamp
The audit should be "queryable" for the admin panel

**Comment by RePierre** [comment]
Where do we store the logs, in the same database?

**Comment by RePierre** [comment]
As discussed on the phone with @alexchiraples:
- the logs will be saved in the same database (will be migrated later)
- if the audit throws an exception, the user won't be able to login
