### ISSUE TITLE
Spike - How to identity device type in .NET core

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/auth-sso#25]
Use case 1: iphone safari - logged on 2016-10-26 14:42 
Use case 2: Your devices - iphone, windows phone, windows PC & galaxy tab 4

**Comment by RePierre** [comment]
As stated in this [SO answer](http://stackoverflow.com/a/32947785) we can use [http://detectmobilebrowsers.com](http://detectmobilebrowsers.com) for detecting mobile browsers.

**Comment by dmihaita** [comment]
Just a thought : that script seems a little bit outdated (Regex updated: 1 August 2014). Shouldn't the application just store the HTTP_USER_AGENT and use a backend solution (device database, etc) to identify the device type?

**Comment by RePierre** [comment]
@dmihaita, that sounds good. We need to see if such databases are available and maybe see if there's a public/free API for that, in order to avoid database maintenance overhead.

**Comment by alexchiraples** [comment]
@RePierre this is something you could use: https://github.com/piwik/device-detector

**Comment by RePierre** [comment]
I found another solution [https://51degrees.com/resources/downloads/open-source-apis](https://51degrees.com/resources/downloads/open-source-apis). I'll see how easily both can be integrated.
