### ISSUE TITLE
Setup docker

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/auth-sso#3]
- [ ] IdentityServer Web App (.NET Core)
- [ ] Admin panel (AngularJS connecting to IdentityServer)
- [ ] MySQL
- [ ] NGINX

**Comment by alexchiraples** [comment]
- [ ] IdentityServer Web App (.NET Core)
- [ ] Backpanel (AngularJS connecting to IdentityServer)
- [ ] MySQL
- [ ] NGINX

**Comment by gpgabriel** [comment]
Consider ca Angular nu este potrivit intr-un astfel de proiect. Aceasta aplicatie presupun ca va fi folosita de toate celelalte aplicatii si ar trebui sa fie suportata pe orice platforma. Angular e prea mare si nu e compatibil cu orice platforma. Solutia cred ca e plain JS pentru ca partea de UI nu este foarte complexa.

**Comment by alexchiraples** [comment]
Issue migrated to civictechro/auth-sso#3
