### ISSUE TITLE
Spike - resource localization for API and controllers in .NET core

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/auth-sso#36]
Starting points: 
https://docs.asp.net/en/latest/fundamentals/localization.html
https://github.com/damienbod/AspNet5Localization

**Comment by dmihaita** [comment]
Daca nu are nimeni nimic impotriva pachetului de localizare oferit de Damien Bod ([nuget](https://www.nuget.org/packages/Localization.SqlLocalizer/)), atunci as putea incepe integrarea. Pareri ?

**Comment by dmihaita** [comment]
Am integrat pachetul de localizare, impreuna cu o pagina de download/upload pentru string'uri in format CSV (oferit tot de Damien Bod). 
Se cunoaste cumva lista culturilor care vor fi suportate de aplicatie?

**Comment by alexchiraples** [comment]
Pentru inceput doar RO. Vom face EN cand ne integram cu un app ce are si en.

**Comment by timotei** [comment]
@dmihaita Care ar fi beneficiile comparate cu localizarea standard oferită de .NET?

**Comment by dmihaita** [comment]
@timotei Folosim localizarea standard oferita de .Net, numai sursa traducerilor este diferita, in loc de fisiere resx va fi o tabela in baza de date. Avantajul major, din punctul meu de vedere, este ca putem decupla procesul de localizare de life-cycle'ul aplicatiei, nemaifiind necesara compilarea si deploy'ul unei noi versiuni, localizarea mesajelor putand avea loc dupa deployment, sau chiar schimbarea unei traduceri nu va necesita o noua compilare.
