### ISSUE TITLE
[Tech] Database update

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/auth-sso#58]
Draft sql script for diagram:
[db_diagram.zip](https://github.com/gov-ithub/auth-sso/files/594084/db_diagram.zip)

Draft DB Diagram
![db_diagram](https://cloud.githubusercontent.com/assets/22675415/20340498/68b985a2-abea-11e6-9b48-aed12bc5a34d.png)

**Comment by dmihaita** [comment]
Se pot comasa tabelele organizationusers si organizationadmins intr-una singura, cu aceeasi structura  cu a tabelei organizationusers, dar cu inca o coloana in plus , Level care sa diferentieze intre admin si regular users?

**Comment by RePierre** [comment]
Imho, nu trebuie să împărțim utilizatorii în admini și restul. Orice organizație are o ierarhie unde fiecare nivel are anumite restricții (funcționarul pregătește dosarul și doar directorul executiv aprobă etc.). Aceste cazuri pot fi modelate mult mai elegant cu definirea de scopes și de drepturi de acces al utilizatorilor la aceste scopes.

**Comment by dmihaita** [comment]
Total de acord. Eu am inteles ca ar fi de fapt o separare logica intre admin si restul rolurilor. Oricum, la momentul actual, cand nu avem definite o lista de roluri si scopuri, se face o diferentiere simpla intre un user cu privilegii si unul fara. Sunt sigur ca odata cu adaugarea functionalitatilor si a clientilor vor deveni destul de clare rolurile si scopurile necesare.

**Comment by alexchiraples** [comment]
Dap @RePuerre si @dmihaita. Adminii si userii sunt deja uniti. Voi adauga o diagrama actualizata

**Comment by alexchiraples** [comment]
![db_diagram](https://cloud.githubusercontent.com/assets/22675415/21264035/bace4308-c3a2-11e6-8e41-a8a5132de2ca.png)
