### ISSUE TITLE
Va putea rula și sub Mono pe Linux cu aceeași eficiență și fără mari diferențe la compilare?

### ISSUE THREAD

**Issue by florinj** [gov-ithub/auth-sso#71]
Întrebarea mea e legată de principiul impus aici (it-hub) pentru tehnologiile utilizate să fie: captive sau libere în/de componente proprietare?

**Comment by timotei** [comment]
@florinj Se folosește [.NET Core](https://www.microsoft.com/net/core) pentru implementare, care este nativ și pe OS X și pe Linux.

**Comment by florinj** [comment]
OK.  Mulțumesc pt. clarificare.
