### ISSUE TITLE
DirectoryNotFoundException in DeviceDetector

### ISSUE THREAD

**Issue by aoancea** [gov-ithub/auth-sso#75]
The issue is being caused by the missing files from the project:

- wwwroot\device-detection\browsers.yml
- wwwroot\device-detection\mobiles.yml
- wwwroot\device-detection\oss.yml

**Short term fix**
You can fix the issue by downloading these files and placing them inside the `wwwroot\device-detection` folder from [https://github.com/piwik/device-detector](https://github.com/piwik/device-detector), the actual files being:
- https://github.com/piwik/device-detector/blob/master/regexes/client/browsers.yml
- https://github.com/piwik/device-detector/blob/master/regexes/device/mobiles.yml
- https://github.com/piwik/device-detector/blob/master/regexes/oss.yml

**Long term fix**
The case when the files are missing should be handled thus not impairing the registration/authentication process

**Comment by alexchiraples** [comment]
am rezolvat ruland `git submodule update` in folder-ul device-detection

**Comment by RePierre** [comment]
Prima dată mi-a mers și mie așa. Dar dacă șterg sursele și dau clone din nou nu merge (cel puțin la mine).

**Comment by alexchiraples** [comment]
Sunt cache-uite date in folderul .git al repo-ului. Trebuie facuta "curatenie" acolo daca stergi folderul cu dependinte

**Comment by aoancea** [comment]
Eu stiu ca rezolvasem problema prin #78 deoarece nu rula bundling-ul si deci nu importa fisierele.
